language: ruby
dist: trusty
sudo: required
rvm:
  - 2.4.2
cache: bundler
addons:
  postgresql: "9.6"
services:
  - redis-server
install:
  - bin/bundle --without development
before_script:
  - bin/rails db:setup
script: bin/rails test
