version: '3'
services:
  db:
    image: postgres:10-alpine
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      ENABLE_ACTIVE_ADMIN: "true"
      RAILS_LOG_TO_STDOUT: "true"
volumes:
  postgres-data:
